version: '3'
services:
  web:
    container_name: podcast_metadata
    build: .
    volumes:
      - ./db.sqlite:/usr/src/app/db.sqlite
      - ./static/uploads:/usr/src/app/static/uploads
    ports:
      - "8000:8000"
